// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndjgdelnvnzsmpjkfkum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kamdkZWxudm56c21wamtma3VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNTgxMjUsImV4cCI6MjA2MjgzNDEyNX0.xoAIZSD54cSp3gq1KF1kUzek3ATca2R5UEluYcahEMs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);