// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqtsvihaofcoyrxyxpiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxdHN2aWhhb2Zjb3lyeHl4cGl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2OTEwMzQsImV4cCI6MjA2MzI2NzAzNH0.frPDTG9rty9kgmM1qTs8AAbQ5KasIV7kXIA8WiU-FEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);